In [1]:
import cv2
from tensorflow.keras.models import load_model
import numpy as np


In [2]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model("D:/Archana/model.h5")

In [3]:
%pip install --upgrade opencv-python


Note: you may need to restart the kernel to use updated packages.


In [4]:
import cv2
cap = cv2.VideoCapture(1)
ret, frame = cap.read()
ret

False

In [5]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)

    # Get the height and width of the frame
    height, width, _ = frame.shape
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        


    
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()
    

1/1 [==============================] - 3s 3s/step
[[0.74108225 0.2589177 ]]
1/1 [==============================] - 0s 200ms/step
[[0.60451525 0.39548475]]
1/1 [==============================] - 0s 176ms/step
[[0.76413363 0.23586637]]
1/1 [==============================] - 0s 158ms/step
[[0.57145697 0.42854297]]
1/1 [==============================] - 0s 92ms/step
[[0.8390152  0.16098478]]
1/1 [==============================] - 0s 109ms/step
[[0.599695   0.40030497]]
1/1 [==============================] - 0s 76ms/step
[[0.2950878 0.7049122]]
1/1 [==============================] - 0s 87ms/step
[[0.46785823 0.53214175]]
1/1 [==============================] - 0s 62ms/step
[[0.66208035 0.33791962]]
1/1 [==============================] - 0s 56ms/step
[[0.64372337 0.35627654]]
1/1 [==============================] - 0s 68ms/step
[[0.5243512  0.47564882]]
1/1 [==============================] - 0s 70ms/step
[[0.74540436 0.25459558]]
1/1 [==============================] - 0s 66ms/step
[[0.46719506

In [8]:
import pygame
from pygame import mixer

mixer.init()
sound= mixer.Sound("D:/project/alarm.wav")
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    if not ret:  # Check if frame was read successfully
        break
    
    height,width = frame.shape[0:2]
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    cv2.rectangle(frame, (0,height-50),(200,height),(0,0,0),thickness=cv2.FILLED)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(frame,pt1=(ex,ey),pt2=(ex+ew,ey+eh), color= (255,0,0), thickness=3 )
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)
        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        
        # if eyes are closed
        if prediction[0][0]>0.30:
            cv2.putText(frame,'closed',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score=Score+1
            if(Score>15):
                try:
                    sound.play()
                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.30:
            cv2.putText(frame,'open',(10,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)      
            cv2.putText(frame,'Score'+str(Score),(100,height-20),fontFace=cv2.FONT_HERSHEY_COMPLEX_SMALL,fontScale=1,color=(255,255,255),
                       thickness=1,lineType=cv2.LINE_AA)
            Score = Score-1
            if (Score<0):
                Score=0
            
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

pygame 2.5.2 (SDL 2.28.3, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
1/1 [==============================] - 0s 54ms/step
[[0.4669869 0.5330131]]
1/1 [==============================] - 0s 58ms/step
[[0.4867075 0.5132925]]
1/1 [==============================] - 0s 45ms/step
[[0.6820631  0.31793693]]
1/1 [==============================] - 0s 58ms/step
[[0.581584   0.41841605]]
1/1 [==============================] - 0s 57ms/step
[[0.5725     0.42749992]]
1/1 [==============================] - 0s 48ms/step
[[0.5600803  0.43991977]]
1/1 [==============================] - 0s 48ms/step
[[0.46946013 0.5305399 ]]
1/1 [==============================] - 0s 54ms/step
[[0.6517582  0.34824178]]
1/1 [==============================] - 0s 54ms/step
[[0.550881   0.44911897]]
1/1 [==============================] - 0s 43ms/step
[[0.6406241  0.35937592]]
1/1 [==============================] - 0s 46ms/step
[[0.54989934 0.45010063]]
1/1 [============================